// Export functions for STL and SCAD
const Exporters = {
  exportSTL: function(geometry, filename = 'geometric_image.stl') {
    debugLog(`Exporting STL: ${filename}`);
    
    if (!geometry) {
      debugLog('ERROR: No geometry to export', 'error');
      alert('No geometry available to export. Please generate the model first.');
      return false;
    }
    
    try {
      let stl = 'solid geometric_image\n';
      
      const { vertices, indices } = geometry;
      
      debugLog(`Processing ${indices.length / 3} triangles for STL...`);
      
      for (let i = 0; i < indices.length; i += 3) {
        const i1 = indices[i] * 3;
        const i2 = indices[i + 1] * 3;
        const i3 = indices[i + 2] * 3;
        
        const v1 = [vertices[i1], vertices[i1 + 1], vertices[i1 + 2]];
        const v2 = [vertices[i2], vertices[i2 + 1], vertices[i2 + 2]];
        const v3 = [vertices[i3], vertices[i3 + 1], vertices[i3 + 2]];
        
        // Calculate normal
        const dx1 = v2[0] - v1[0], dy1 = v2[1] - v1[1], dz1 = v2[2] - v1[2];
        const dx2 = v3[0] - v1[0], dy2 = v3[1] - v1[1], dz2 = v3[2] - v1[2];
        const nx = dy1 * dz2 - dz1 * dy2;
        const ny = dz1 * dx2 - dx1 * dz2;
        const nz = dx1 * dy2 - dy1 * dx2;
        const len = Math.sqrt(nx * nx + ny * ny + nz * nz) || 1;
        
        stl += `  facet normal ${(nx / len).toFixed(6)} ${(ny / len).toFixed(6)} ${(nz / len).toFixed(6)}\n`;
        stl += `    outer loop\n`;
        stl += `      vertex ${v1[0].toFixed(3)} ${v1[1].toFixed(3)} ${v1[2].toFixed(3)}\n`;
        stl += `      vertex ${v2[0].toFixed(3)} ${v2[1].toFixed(3)} ${v2[2].toFixed(3)}\n`;
        stl += `      vertex ${v3[0].toFixed(3)} ${v3[1].toFixed(3)} ${v3[2].toFixed(3)}\n`;
        stl += `    endloop\n`;
        stl += `  endfacet\n`;
      }
      
      stl += 'endsolid geometric_image\n';
      
      debugLog(`STL file generated: ${stl.length} bytes`);
      
      const blob = new Blob([stl], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = filename;
      a.click();
      URL.revokeObjectURL(url);
      
      debugLog('STL file downloaded successfully');
      return true;
      
    } catch (error) {
      debugLog(`ERROR exporting STL: ${error.message}`, 'error');
      alert(`Failed to export STL: ${error.message}`);
      return false;
    }
  },
  
  exportSCAD: function(geometry, config, filename = 'geometric_image.scad') {
    debugLog(`Exporting SCAD: ${filename}`);
    
    if (!geometry) {
      debugLog('ERROR: No geometry to export', 'error');
      alert('No geometry available to export. Please generate the model first.');
      return false;
    }
    
    try {
      let scad = `// Parametric Geometric Image Relief
// Generated by 3D Geometric Relief Generator
// ${new Date().toISOString()}

// ========================================
// PARAMETERS - Adjust these values
// ========================================

// Dimensions
width = ${config.width};
height = ${config.height};
max_height = ${config.maxHeight};
base_thickness = ${config.baseThickness};

// Shape settings
shape_type = "${config.shapeType}";
min_shape_size = ${config.minShapeSize};
max_shape_size = ${config.maxShapeSize};

// Light direction settings
light_source = "${config.lightSource}"; // ceiling, left, right, front, back
tilt_angle = ${config.tiltAngle}; // degrees

// Image processing
contrast = ${config.contrast};
height_exaggeration = ${config.heightExaggeration};
preprocess_contrast = ${config.preprocessContrast};

// ========================================
// GEOMETRY DATA
// ========================================

module geometric_relief() {
  polyhedron(
    points = [\n`;
      
      const { vertices } = geometry;
      
      debugLog(`Writing ${vertices.length / 3} vertices to SCAD...`);
      
      for (let i = 0; i < vertices.length; i += 3) {
        scad += `      [${vertices[i].toFixed(3)}, ${vertices[i + 1].toFixed(3)}, ${vertices[i + 2].toFixed(3)}]`;
        if (i < vertices.length - 3) scad += ',';
        scad += '\n';
      }
      
      scad += `    ],\n    faces = [\n`;
      
      const { indices } = geometry;
      
      debugLog(`Writing ${indices.length / 3} faces to SCAD...`);
      
      for (let i = 0; i < indices.length; i += 3) {
        scad += `      [${indices[i]}, ${indices[i + 1]}, ${indices[i + 2]}]`;
        if (i < indices.length - 3) scad += ',';
        scad += '\n';
      }
      
      scad += `    ]
  );
}

// ========================================
// RENDER
// ========================================

geometric_relief();

// Statistics:
// - Vertices: ${vertices.length / 3}
// - Faces: ${indices.length / 3}
// - Generated: ${new Date().toLocaleString()}
`;
      
      debugLog(`SCAD file generated: ${scad.length} bytes`);
      
      const blob = new Blob([scad], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = filename;
      a.click();
      URL.revokeObjectURL(url);
      
      debugLog('SCAD file downloaded successfully');
      return true;
      
    } catch (error) {
      debugLog(`ERROR exporting SCAD: ${error.message}`, 'error');
      alert(`Failed to export SCAD: ${error.message}`);
      return false;
    }
  }
};

debugLog('Exporters loaded');